version: '3.8'
services:
  db:
    container_name: dev_pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: root
      POSTGRES_DB: datingapp
    ports:
      - "5432:5432"
  pgadmin:
    container_name: dev_pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"